### ISSUE TITLE
Refer to F4PGA workgroup page from the description

### ISSUE THREAD

**Issue by robmains** [chipsalliance/chips-alliance-website#12]
The F4PGA workgroup should have its website, https://www.f4pga.org listed

**Comment by cjyabraham** [comment]
@robmains is that the correct url? It doesn't currently work for me.

**Comment by robmains** [comment]
Does this work? 

https://f4pga.org/

**Comment by mgielda** [comment]
Yes, only the latter works

**Comment by cjyabraham** [comment]
I've added it: https://chipsalliance.github.io/chips-alliance-website/workgroups/
