### ISSUE TITLE
Push PR preview to gh-pages branch Github Action Is Broken

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/chips-alliance-website#136]
I noticed with this [PR](https://github.com/chipsalliance/chips-alliance-website/pull/135) that the preview link was not working.

Looking at the [github action log](https://github.com/chipsalliance/chips-alliance-website/actions/runs/11135333479/job/30945218029) I see Download artifacts failing with the following [error](https://github.com/chipsalliance/chips-alliance-website/actions/runs/11135333479/job/30945218029#step:3:55)

`Error: Unhandled error: HttpError: ﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ca05c309-701e-0091-395e-14bf13000000
Time:2024-10-02T00:00:45.1789487Z</Message></Error>`

@tgorochowik  if you have time to poke around on this, that would be awesome, if not I can try and solve.

**Comment by tgorochowik** [comment]
Thanks to the report, it is most likely related to the recent gh api for artifacts deprecation, we need to migrate to github's built-in actions for uploading and downloading the artifacts, ref: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

I should be able to help with this later this week, but please feel free to take a look at it sooner if you wish to.

**Comment by bensternthal** [comment]
I think this is resolved, at some point I need to learn how to test Github actions locally (on a mac).
