### ISSUE TITLE
Governing Board autogeneration

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/chips-alliance-website#19]
The data for the governing board uses shortcodes and is better than the companies list, but still not ideal: https://raw.githubusercontent.com/chipsalliance/chips-alliance-website/6aecb7f4f00988b6db7aae780ae8c9d3134a80e6/content/about/governance.md

Parsing this automatically would be a pain. Also, board reps are derivatives of the companies status. So we might want to keep the board rep data together with the membership data, i.e. add a "board_rep" key or sth like that to the YAML for members. As for photos, they could simply have the following form name_surname.png or sth and this way you would not have to even include that data in the YAML.

There are little corner cases like a silver member board rep but I assume that basically if there is a "board_rep" key on the members side, whoever is indicated just gets added to the board composition (if no photo available, then a placeholder with a head).

**Comment by cjyabraham** [comment]
So all board reps would be listed in the members yaml due to them being associated with a member? Or are there some people who are on the board who would not otherwise be listed in the members yaml?

**Comment by mgielda** [comment]
I am 99% sure the only extra board reps are me (non-voting) and Henry, head of the TSC (voting). But I think we can ignore this for now. We can manually add those ourselves on top of the "for" loop that lists everyone else.

**Comment by mgielda** [comment]
I would just go ahead and add the relevant mechanism and data in place, using https://chipsalliance.org/about/governance/ as reference. Every platinum member should have a rep. Of course 

Ah, and there is also Rob. But again, we will add him manually. We need the pictures for him, Henry and myself in the repo as well for that. @hcook can you provide a photo - only yours is missing.

**Comment by mgielda** [comment]
(but let's just assume we don't block on anything at this point, just move forward with the data we have)

**Comment by mgielda** [comment]
Actually, I can see Henry, myself and Rob are in different sections of governance, so it's probably OK to just skip us in the "governing board" section, so this could be fully autogenerated. Requested an up-to-date list and will populate the YAML when we have that.

**Comment by alenacal** [comment]
use a placeholder image for people who don't have a headshot

**Comment by cjyabraham** [comment]
use Hugo function to generate the image filename
