### ISSUE TITLE
Adapt website copy to new design

### ISSUE THREAD

**Issue by cjyabraham** [chipsalliance/chips-alliance-website#2]
Do you have a marketing person I can work with to adapt the copy of the existing CHIPS site to the new design? There are a lot of dynamic modules in [the new design](https://jovial-pipe.cloudvent.net/) that I think it would be great to take advantage of, however, it would take some work to adapt the current messaging.

**Comment by martin-kaczmarek** [comment]
Hi Chris!

Not sure if this issue is still valid, but in case so, myself, @clabedzka and @robmains can help. Please point to any specific modules that need re-wording.

**Comment by cjyabraham** [comment]
This overall content review is now being done so I'll close this general issue in favor of the specific ones that are now being created.
