### ISSUE TITLE
Create autogenerated Workgroups list

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/chips-alliance-website#22]
Currently the [WG list](https://chipsalliance.github.io/chips-alliance-website/workgroups/) is a copy-paste from the previous website. We definitely want to change this and populate it from the TSC repo.

We will clean up the data to prepare it to be automatically parsed. The files will be markdown with YAML frontmatter: we want the front-matter to contain standard data (e.g. WG name, leader, meetings list) which should be nicely rendered on the page and some Markdown which should be rendered as-is.

**Comment by mgielda** [comment]
@kgugala that is on you.

**Comment by alenacal** [comment]
@cjyabraham to implement mechanism to display

**Comment by mgielda** [comment]
Let's assume that when a piece of data is not available, it just does not display.

**Comment by cjyabraham** [comment]
@martin-kaczmarek, did you intentionally not create a file for the RISC-V DV, SystemVerilog, Interconnects, and Cores workgroups that [are listed here](https://chipsalliance.org/workgroups/)?

**Comment by cjyabraham** [comment]
This is done.
