### ISSUE TITLE
Events: Slides of Fall 2022 CHIPS event should be Fall 2021

### ISSUE THREAD

**Issue by robmains** [chipsalliance/chips-alliance-website#25]
This should be for fall 2021, not 2022.

**Comment by mgielda** [comment]
Hi Rob, I think this can be fixed by editing:

https://github.com/chipsalliance/chips-alliance-website/blob/main/content/events/chips-biannual-technology-update-2022-2.md

Do you have this data somewhere?

**Comment by robmains** [comment]
I do have all the data in Google drive as Github won’t handle large presentation files, as I learned. 
Here is a link to the drive folders:

https://drive.google.com/drive/u/0/folders/1tjGCIGhUUrfNl2oYFkqY5in2d7ljWE5_￼

I thought I had edited this file earlier and submitted a pull request, but perhaps there were some issues. 
I am meeting with Chris Friday evening to have him help me setup a dev environment. I do see that some of the work I did was uploaded, but also see there are still problems as you correctly mention. 

I can look at revising this later today.

Thanks,

Rob

Rob Mains
General Manager
CHIPS Alliance


***@***.***
(c) +1.408.607.4879

**Comment by robmains** [comment]
I’ve updated the video link and slide links for the December 2022 CHIPS fall event. Unfortunately, not all the presenters contributed their slides even after repeated requests.

Thanks,

Rob

Rob Mains
General Manager
CHIPS Alliance


***@***.***
(c) +1.408.607.4879

**Comment by mgielda** [comment]
Perfect, this solves the issue then. We can chase people up for slides later.
