### ISSUE TITLE
Requirements for Events

### ISSUE THREAD

**Issue by cjyabraham** [chipsalliance/chips-alliance-website#3]
Can you expand on the requirements you have for the Events page? Do you want that to just be a static page of events you can edit freely, a page with an embedded calendar ([example](https://www.cncf.io/calendar/)), or something else?

**Comment by mgielda** [comment]
Hi @cjyabraham I think our events are not happening as often as say CNCF's so a calendar would be an overkill. A list of files of some sort would do, latest first, either leading to a specific page with details or with the details listed already on the main page. The CHIPS website used to have events as a list with relevant links etc but that broke and we haven't restored it in anticipation of the new website.

**Comment by mgielda** [comment]
So I guess my answer is static page of events, including links to registration etc for future events and links to materials for old ones.

**Comment by cjyabraham** [comment]
Sounds fine. Could someone send me the content for that please?

**Comment by martin-kaczmarek** [comment]
@cjyabraham please see https://github.com/chipsalliance/chips-alliance-website/issues/10

**Comment by mgielda** [comment]
OK! So I will close this one in favor of #10.
