### ISSUE TITLE
In Governance, Pierre-Emmanuel's image seems to be missing, but instead of a placeholder we see a "missing image"

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/chips-alliance-website#49]
See below:

![Screenshot from 2023-03-30 17-46-14](https://user-images.githubusercontent.com/140166/228891941-a020efa2-0e7e-436b-8601-c64472f91bff.png)

**Comment by mgielda** [comment]
Since we don't have an image for him yet, the page should display a placeholder.

**Comment by cjyabraham** [comment]
I have just been manually making a copy of the generic profile photo to serve as a placeholder until a proper photo is found.

**Comment by cjyabraham** [comment]
I've improved this to dynamically check whether the profile image exists and use the generic one if not.
